Fix for Issue 301 and 300
HewlettPackard/terraform-provider-oneview pull request #302
Opened 2021-05-02 19:39 UTC by AsisBagga

### Description
Fixed Attribute Types

### Issues Resolved
#301 
#300 

### Check List
- [ ] New functionality includes testing.
  - [ ]  All tests pass for go 1.11 + gofmt checks.
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [ ] New endpoints supported are updated in the endpoints-support.md file.
- [ ] Changes are documented in the CHANGELOG.

2021-05-03 07:48 UTC, Schluggi approved these changes
Looks like an easy fix 👍

2021-05-03 07:55 UTC, Schluggi requested changes
I think it is a good idea to remove the default value of the affinity in the template as well.

2021-05-12 06:11 UTC, nabhajit-ray approved these changes

2021-05-12 06:20 UTC, yuvirani approved these changes

2021-05-12 09:49 UTC, merged